revert: "refactor: Clean up golden-layout css (#1322)" (#1334)
This reverts commit d1838d7151e31de1e26da8b60f336e991bb25404.

Was getting build errors when consuming in Enterprise:
```
> Task :web-client-ui:ideClient FAILED
✓ 1043 modules transformed.
Could not resolve '../scss/GoldenLayout.module.css' from node_modules/@deephaven/golden-layout/dist/GoldenLayoutThemeExport.js
error during build:
Error: Could not resolve '../scss/GoldenLayout.module.css' from node_modules/@deephaven/golden-layout/dist/GoldenLayoutThemeExport.js
    at error (file:///Users/bender/dev/illumon/iris/web/client-ui/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.handleResolveId (file:///Users/bender/dev/illumon/iris/web/client-ui/node_modules/rollup/dist/es/shared/rollup.js:22156:24)
    at file:///Users/bender/dev/illumon/iris/web/client-ui/node_modules/rollup/dist/es/shared/rollup.js:22119:26
ERROR: "build-js" exited with 1.
```

In the `dist/GoldenLayoutThemeExport.js`, the import ends up being:
```
import GoldenLayout from "../scss/GoldenLayout.module.css"; // parseInt for unitless values, stripping "px"
```
But in the scss folder it’s `GoldenLayout.module.scss`, not `.css`

The babel preset converts the scss imports to css:
```
    [
      'transform-rename-import',
      {
        // The babel-plugin-add-import-extension adds the .js to .scss imports, just convert them back to .css
        original: '^(.+?)\\.s?css.js$',
        replacement: '$1.css',
      },
    ],
```

Will need to resolve this issue before re-merging this refactor.